version: '2'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      LANG: ja_JP.UTF-8
    volumes:
      - /.data/boardless/:/var/lib/postgresql/data:Z
    networks:
      - my-network
    ports:
      - '5432:5432'
  deploys-db:
    image: tampopos/boardless-deploys-db:4.0.1
    environment:
      - ConnectionStrings__Root=Server=postgres;User ID=postgres;Password=postgres;Port=5432;
      - Directory=./.migration
    networks:
      - my-network
    depends_on:
      - postgres
    links:
      - postgres
  api:
    build: .
    image: tampopos/template-api
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres;User ID=postgres;Password=postgres;Port=5432;Database=boardless;
    networks:
      - my-network
    links:
      - postgres
    depends_on:
      - deploys-db
    ports:
      - '8080:80'
networks:
  my-network:
