version: 2.1
executors:
  dotnet:
    docker:
      - image: microsoft/dotnet:latest
      - image: postgres:latest
        environment:
          LANG: ja_JP.UTF-8
          POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
      - image: tampopos/boardless-deploys-db:2.0.0
  dind:
    docker:
      - image: docker:latest
jobs:
  build:
    executor: dotnet
    steps:
      - checkout
      - run:
          name: build
          command: dotnet build Api
  test:
    executor: dotnet
    steps:
      - checkout
      - run:
          name: test
          command: dotnet test Domain.Tests
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
      - run:
          name: Wait for app
          command: dockerize -wait tcp://127.0.0.1:80 -timeout 1m
      - run:
          name: migration
          command: .docker/deploys/migration.sh 127.0.0.1:80 60
      - run:
          name: test
          command: dotnet test Infrastructure.Data.Tests
  publish:
    executor: dind
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t tampopos/template-api:${CIRCLE_TAG} .
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push tampopos/template-api:${CIRCLE_TAG}
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          context: docker-publish
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
