version: 2.1
executors:
  dotnet:
    docker:
      - image: microsoft/dotnet:latest
  dind:
    docker:
      - image: docker:latest
jobs:
  build:
    executor: dotnet
    steps:
      - checkout
      - run:
          name: build
          command: dotnet build Api
  test:
    executor: dotnet
    steps:
      - checkout
      - run:
          name: test
          command: dotnet test Domain.Tests
  publish:
    executor: dind
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t tampopos/template-api:${CIRCLE_TAG} .
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push tampopos/template-api:${CIRCLE_TAG}
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          context: docker-publish
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
